import os
import psycopg2
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

def get_connection():
    """Establish a connection to the database using DATABASE_URL and return it."""
    try:
        conn = psycopg2.connect(DATABASE_URL)
        return conn
    except Exception as e:
        print(f"Error connecting to database: {e}")
        return None

if __name__ == "__main__":
    conn = get_connection()
    if conn:
        print("Successfully connected to the database!")
        conn.close()
    else:
        print("Failed to connect to the database.")

# generated by chatGPT